---
deployment:
  tasks:
    - rm -rf /home/powerxsl68a4/powerxsleep/*
    - /bin/cp -r ./powerxsleep/* /home/powerxsl68a4/powerxsleep/

    - rm -rf /home/powerxsl68a4/public_html/*
    - /bin/cp -r ./public_html/* /home/powerxsl68a4/public_html/
