---
deployment:
  tasks:
    # 1. Định nghĩa đường dẫn gốc và Danh sách File cần bảo vệ
    - export DEPLOYPATH=/home/powerxsl68a4/
    
    # Định nghĩa các file và thư mục cần bảo vệ trong một biến duy nhất.
    # Định dạng: "file_hoặc_thu_muc:thu_muc_goc"
    - export PROTECTED_ITEMS="writable:powerxsleep uploads:public_html .env:powerxsleep .htaccess:public_html"
    
    # 2. DI CHUYỂN DỮ LIỆU VÀ CẤU HÌNH ĐI (Sử dụng VÒNG LẶP)
    - |
      for item in $PROTECTED_ITEMS; do
        NAME=$(echo $item | cut -d: -f1)
        SOURCE_DIR=$(echo $item | cut -d: -f2)
        FULL_PATH=$DEPLOYPATH/$SOURCE_DIR/$NAME
        
        # Kiểm tra xem đó là file (-f) hay thư mục (-d)
        if [ -f $FULL_PATH ] || [ -d $FULL_PATH ]; then
          /bin/mv $FULL_PATH $DEPLOYPATH/data/
        fi
      done

    # 3. XÓA SẠCH THƯ MỤC CODE CŨ
    - rm -rf $DEPLOYPATH/powerxsleep/*
    - rm -rf $DEPLOYPATH/public_html/*

    # 4. SAO CHÉP CODE MỚI
    - /bin/cp -r ./powerxsleep/* $DEPLOYPATH/powerxsleep/
    - /bin/cp -r ./public_html/* $DEPLOYPATH/public_html/

    # 5. PHỤC HỒI DỮ LIỆU VÀ CẤU HÌNH VỀ VỊ TRÍ CŨ (Sử dụng VÒNG LẶP)
    - |
      for item in $PROTECTED_ITEMS; do
        NAME=$(echo $item | cut -d: -f1)
        TARGET_DIR=$(echo $item | cut -d: -f2)
        
        DATA_PATH=$DEPLOYPATH/data/$NAME
        TARGET_PATH=$DEPLOYPATH/$TARGET_DIR/
        
        if [ -f $DATA_PATH ]; then
          # PHỤC HỒI FILE (dùng mv để ghi đè)
          /bin/mv -f $DATA_PATH $TARGET_PATH
        elif [ -d $DATA_PATH ]; then
          # PHỤC HỒI THƯ MỤC (dùng cp và rm)
          /bin/cp -r $DATA_PATH $TARGET_PATH
          /bin/rm -rf $DATA_PATH
        fi
      done
