---
deployment:
  tasks:
    # 1. Định nghĩa đường dẫn gốc để code gọn hơn
    - export DEPLOYPATH=/home/powerxsl68a4/

    # 2. DI CHUYỂN DỮ LIỆU ĐI (Nếu tồn tại)
    # Di chuyển 'writable'
    - |
      if [ -d $DEPLOYPATH/powerxsleep/writable ]; then
        /bin/mv $DEPLOYPATH/powerxsleep/writable $DEPLOYPATH/data/
      fi
    # Di chuyển 'uploads'
    - |
      if [ -d $DEPLOYPATH/public_html/uploads ]; then
        /bin/mv $DEPLOYPATH/public_html/uploads $DEPLOYPATH/data/
      fi

    # 3. XÓA SẠCH THƯ MỤC CODE CŨ
    # Xóa sạch nội dung thư mục powerxsleep (không xóa thư mục chính)
    - rm -rf $DEPLOYPATH/powerxsleep/*
    # Xóa sạch nội dung thư mục public_html (không xóa thư mục chính)
    - rm -rf $DEPLOYPATH/public_html/*

    # 4. SAO CHÉP CODE MỚI
    # Sao chép code từ thư mục Git cục bộ (ví dụ: thư mục powerxsleep)
    - /bin/cp -r ./powerxsleep/* $DEPLOYPATH/powerxsleep/
    # Sao chép code từ thư mục Git cục bộ (ví dụ: thư mục public_html)
    - /bin/cp -r ./public_html/* $DEPLOYPATH/public_html/

    # 5. DI CHUYỂN DỮ LIỆU VỀ (Sử dụng Copy và Remove)
    # Sao chép 'writable' trở lại và xóa bản gốc trong /data/
    - |
      if [ -d $DEPLOYPATH/data/writable ]; then
        /bin/cp -r $DEPLOYPATH/data/writable $DEPLOYPATH/powerxsleep/
        /bin/rm -rf $DEPLOYPATH/data/writable
      fi
    # Sao chép 'uploads' trở lại và xóa bản gốc trong /data/
    - |
      if [ -d $DEPLOYPATH/data/uploads ]; then
        /bin/cp -r $DEPLOYPATH/data/uploads $DEPLOYPATH/public_html/
        /bin/rm -rf $DEPLOYPATH/data/uploads
      fi
