<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run()
    {
        $data = [
            [
                'name'              => 'Nệm Cao Su Thiên Nhiên 1m6x2m',
                'slug'              => 'nem-cao-su-thien-nhien-1m6x2m',
                'sku'               => 'NCS-160200',
                'price'             => 5500000,
                'sale_price'        => 4990000,
                'short_description' => 'Nệm cao su thiên nhiên êm ái, thoáng mát.',
                'description'       => 'Sản phẩm được làm từ 100% cao su thiên nhiên, độ đàn hồi cao, thoáng khí.',
                'stock_quantity'    => 20,
                'highlights'        => json_encode(['Cao su thiên nhiên', 'Độ bền cao', 'Thoáng mát']),
                'meta_title'        => 'Nệm Cao Su Thiên Nhiên',
                'meta_description'  => 'Nệm cao su thiên nhiên chính hãng, bảo hành 10 năm.',
                'status'            => 1,
                'created_at'        => date('Y-m-d H:i:s'),
                'updated_at'        => date('Y-m-d H:i:s'),
            ],
            [
                'name'              => 'Nệm Lò Xo Túi 1m8x2m',
                'slug'              => 'nem-lo-xo-tui-1m8x2m',
                'sku'               => 'NLX-180200',
                'price'             => 7200000,
                'sale_price'        => 6500000,
                'short_description' => 'Nệm lò xo túi độc lập, giảm tiếng ồn.',
                'description'       => 'Thiết kế lò xo túi độc lập, nâng đỡ cơ thể hoàn hảo, giảm truyền động.',
                'stock_quantity'    => 15,
                'highlights'        => json_encode(['Lò xo túi độc lập', 'Êm ái', 'Bền bỉ']),
                'meta_title'        => 'Nệm Lò Xo Túi',
                'meta_description'  => 'Nệm lò xo túi cao cấp, phù hợp gia đình.',
                'status'            => 1,
                'created_at'        => date('Y-m-d H:i:s'),
                'updated_at'        => date('Y-m-d H:i:s'),
            ],
            [
                'name'              => 'Nệm Foam Memory 1m6x2m',
                'slug'              => 'nem-foam-memory-1m6x2m',
                'sku'               => 'NFM-160200',
                'price'             => 4800000,
                'sale_price'        => null,
                'short_description' => 'Nệm foam memory nâng đỡ cơ thể.',
                'description'       => 'Công nghệ foam memory hiện đại, ôm sát đường cong cơ thể.',
                'stock_quantity'    => 10,
                'highlights'        => json_encode(['Foam memory', 'Êm ái', 'Nâng đỡ tốt']),
                'meta_title'        => 'Nệm Foam Memory',
                'meta_description'  => 'Nệm foam memory, thoải mái, bảo hành 7 năm.',
                'status'            => 1,
                'created_at'        => date('Y-m-d H:i:s'),
                'updated_at'        => date('Y-m-d H:i:s'),
            ],
            [
                'name'              => 'Nệm Bông Ép 1m4x2m',
                'slug'              => 'nem-bong-ep-1m4x2m',
                'sku'               => 'NBE-140200',
                'price'             => 2500000,
                'sale_price'        => 2200000,
                'short_description' => 'Nệm bông ép giá rẻ, dễ vệ sinh.',
                'description'       => 'Sản phẩm làm từ sợi bông ép, độ cứng vừa phải, dễ gấp gọn.',
                'stock_quantity'    => 30,
                'highlights'        => json_encode(['Giá rẻ', 'Dễ gấp gọn', 'Thoáng mát']),
                'meta_title'        => 'Nệm Bông Ép',
                'meta_description'  => 'Nệm bông ép giá tốt, phù hợp sinh viên, phòng trọ.',
                'status'            => 1,
                'created_at'        => date('Y-m-d H:i:s'),
                'updated_at'        => date('Y-m-d H:i:s'),
            ],
            [
                'name'              => 'Nệm Cao Su Tổng Hợp 1m2x2m',
                'slug'              => 'nem-cao-su-tong-hop-1m2x2m',
                'sku'               => 'NCTH-120200',
                'price'             => 3000000,
                'sale_price'        => 2800000,
                'short_description' => 'Nệm cao su tổng hợp, bền bỉ.',
                'description'       => 'Sản phẩm làm từ cao su nhân tạo, giá thành hợp lý.',
                'stock_quantity'    => 25,
                'highlights'        => json_encode(['Cao su tổng hợp', 'Giá hợp lý', 'Độ bền tốt']),
                'meta_title'        => 'Nệm Cao Su Tổng Hợp',
                'meta_description'  => 'Nệm cao su tổng hợp giá rẻ, chất lượng ổn định.',
                'status'            => 1,
                'created_at'        => date('Y-m-d H:i:s'),
                'updated_at'        => date('Y-m-d H:i:s'),
            ],
            [
                'name'              => 'Nệm Foam Cool Gel 1m6x2m',
                'slug'              => 'nem-foam-cool-gel-1m6x2m',
                'sku'               => 'NFCG-160200',
                'price'             => 5200000,
                'sale_price'        => 4900000,
                'short_description' => 'Nệm foam gel mát, thoáng khí.',
                'description'       => 'Kết hợp foam và gel mát, giúp ngủ ngon hơn.',
                'stock_quantity'    => 12,
                'highlights'        => json_encode(['Cool Gel', 'Thoáng khí', 'Êm ái']),
                'meta_title'        => 'Nệm Foam Cool Gel',
                'meta_description'  => 'Nệm foam cool gel thoáng khí, phù hợp mùa hè.',
                'status'            => 1,
                'created_at'        => date('Y-m-d H:i:s'),
                'updated_at'        => date('Y-m-d H:i:s'),
            ],
            [
                'name'              => 'Nệm Cao Su Latex 1m8x2m',
                'slug'              => 'nem-cao-su-latex-1m8x2m',
                'sku'               => 'NCL-180200',
                'price'             => 8500000,
                'sale_price'        => 7900000,
                'short_description' => 'Nệm latex cao cấp nhập khẩu.',
                'description'       => 'Chất liệu latex tự nhiên, thoáng khí, siêu bền.',
                'stock_quantity'    => 8,
                'highlights'        => json_encode(['Latex tự nhiên', 'Thoáng khí', 'Siêu bền']),
                'meta_title'        => 'Nệm Latex',
                'meta_description'  => 'Nệm latex cao cấp, nhập khẩu chính hãng.',
                'status'            => 1,
                'created_at'        => date('Y-m-d H:i:s'),
                'updated_at'        => date('Y-m-d H:i:s'),
            ],
            [
                'name'              => 'Nệm Gấp Du Lịch 1m2x2m',
                'slug'              => 'nem-gap-du-lich-1m2x2m',
                'sku'               => 'NGDL-120200',
                'price'             => 1800000,
                'sale_price'        => 1500000,
                'short_description' => 'Nệm gấp tiện lợi, phù hợp du lịch.',
                'description'       => 'Thiết kế gấp gọn, dễ mang đi xa.',
                'stock_quantity'    => 40,
                'highlights'        => json_encode(['Gấp gọn', 'Tiện lợi', 'Giá rẻ']),
                'meta_title'        => 'Nệm Gấp Du Lịch',
                'meta_description'  => 'Nệm gấp gọn du lịch, tiện lợi, giá tốt.',
                'status'            => 1,
                'created_at'        => date('Y-m-d H:i:s'),
                'updated_at'        => date('Y-m-d H:i:s'),
            ],
            [
                'name'              => 'Nệm Cao Su Non 1m6x2m',
                'slug'              => 'nem-cao-su-non-1m6x2m',
                'sku'               => 'NCSN-160200',
                'price'             => 4200000,
                'sale_price'        => 3900000,
                'short_description' => 'Nệm cao su non êm ái.',
                'description'       => 'Chất liệu cao su non mềm mại, thoáng mát.',
                'stock_quantity'    => 18,
                'highlights'        => json_encode(['Cao su non', 'Êm ái', 'Thoáng khí']),
                'meta_title'        => 'Nệm Cao Su Non',
                'meta_description'  => 'Nệm cao su non chính hãng, êm ái, giá tốt.',
                'status'            => 1,
                'created_at'        => date('Y-m-d H:i:s'),
                'updated_at'        => date('Y-m-d H:i:s'),
            ],
            [
                'name'              => 'Nệm Trẻ Em 1m2x2m',
                'slug'              => 'nem-tre-em-1m2x2m',
                'sku'               => 'NTE-120200',
                'price'             => 2000000,
                'sale_price'        => 1800000,
                'short_description' => 'Nệm dành cho trẻ em, an toàn.',
                'description'       => 'Thiết kế đặc biệt cho trẻ em, an toàn và thoải mái.',
                'stock_quantity'    => 22,
                'highlights'        => json_encode(['An toàn', 'Êm ái', 'Phù hợp trẻ em']),
                'meta_title'        => 'Nệm Trẻ Em',
                'meta_description'  => 'Nệm trẻ em an toàn, chất lượng, giá hợp lý.',
                'status'            => 1,
                'created_at'        => date('Y-m-d H:i:s'),
                'updated_at'        => date('Y-m-d H:i:s'),
            ],
        ];

        // Insert nhiều dòng 1 lần
        $this->db->table('products')->insertBatch($data);
    }
}
